#pragma once
// AfflictionCatalog.h — GENERATED by tools/sekhema/extract_affliction_icons.py
// from Data/Balance/SanctumPersistentEffects (EffectCategory 1|3). DO NOT EDIT;
// re-run the tool on game patches. Icons live in resources/afflictions/*.png.
#include <cstring>

namespace sekhema {

struct AfflictionInfo {
    const char* name;      // EN display name — the weight-table key
    const char* iconFile;  // PNG under resources/afflictions/ ("" if none)
    const char* desc;      // cleaned curse description (may contain '\n')
    bool        major;     // EffectCategory 3 = Major Affliction
};

inline constexpr AfflictionInfo kAfflictions[] = {
    { "Black Smoke", "curseblacksmokeicon.png", "You can see one fewer room ahead on the Trial Map", false },
    { "Blunt Sword", "cursebluntswordicon.png", "You and your Minions deal 40% less Damage", false },
    { "Branded Balbalakh", "afflictionbrandedbalbalakhicon.png", "Cannot restore Honour", true },
    { "Chains of Binding", "cursechainofbindingicon.png", "Monsters inflict Binding Chains on Hit", false },
    { "Chiselled Stone", "cursechiselledstoneicon.png", "Monsters Petrify on Hit", true },
    { "Corrosive Concoction", "cursecorrosiveconcoctionicon.png", "You have no Armour, Evasion and Energy Shield", true },
    { "Costly Aid", "afflictioncostlyaidicon.png", "Gain a random Minor Affliction when you venerate a Maraketh Shrine", false },
    { "Dark Pit", "cursedarkpiticon.png", "Traps deal 100% increased Damage", false },
    { "Deadly Snare", "curseheightenedsecurityicon.png", "Traps deal Triple Damage", true },
    { "Death Toll", "cursedeathtollicon.png", "Monsters no longer drop Sacred Water\nTake X Physical Damage after completing N Rooms\nTake X Physical Damage after completing the next Room", true },
    { "Deceptive Mirror", "cursemirroricon.png", "You are not always taken to the room you select", false },
    { "Dishonoured Tattoo", "afflictiondishonouredtattooicon.png", "100% increased Damage Taken while on Low Life", false },
    { "Exhausted Wells", "afflictionexhaustedwellsicon.png", "Chests no longer grant Sacred Water", false },
    { "Fiendish Wings", "cursefiendishwingsicon.png", "Monsters' Action Speed cannot be slowed below base\nMonsters have 25% increased Attack, Cast and Movement Speed", false },
    { "Forgotten Traditions", "afflictionforgottentraditionsicon.png", "50% reduced Effect of your Non-Unique Relics", false },
    { "Gate Toll", "afflictiongatetollicon.png", "Lose 30 Sacred Water on room completion", false },
    { "Ghastly Scythe", "curseghastlyscytheicon.png", "Losing Honour ends the Trial\n(removed after N rooms)", true },
    { "Glass Shard", "curseglassshardicon.png", "The next Boon you gain is converted into a random Minor Affliction", true },
    { "Golden Smoke", "cursegoldensmokeicon.png", "Rewards are unknown on the Trial Map", false },
    { "Haemorrhage", "afflictionhaemorrhageicon.png", "You cannot restore Honour (removed after killing the next Boss)", false },
    { "Honed Claws", "cursehonedclawsicon.png", "Monsters deal 30% more Damage", false },
    { "Hungry Fangs", "cursehungryfangsicon.png", "Monsters remove 5% of your Life, Mana and Energy Shield on Hit", false },
    { "Iron Manacles", "curseironmanaclesicon.png", "You have no Evasion", false },
    { "Leaking Waterskin", "afflictionleakingwaterskinicon.png", "Lose 20 Sacred Water when you take Damage from an Enemy Hit", false },
    { "Low Rivers", "afflictionlowriversicon.png", "50% less Sacred Water found", false },
    { "Myriad Aspersions", "afflictionmyriadaspersionsicon.png", "When you gain an Affliction, gain an additional random Minor Affliction", false },
    { "Orb of Negation", "curseorbofnegationicon.png", "Non-Unique Relics have no Effect", true },
    { "Orbala's Leathers", "boonmarakethleatherarmouricon.png", "50% less Maximum Honour", true },
    { "Purple Smoke", "cursepurplesmokeicon.png", "Afflictions are unknown on the Trial Map", false },
    { "Rapid Quicksand", "curserapidquicksandicon.png", "Traps are faster", false },
    { "Red Smoke", "curseredsmokeicon.png", "Room types are unknown on the Trial Map", false },
    { "Rusted Mallet", "curserustedmalleticon.png", "Monsters always Knockback\nMonsters have increased Knockback Distance", false },
    { "Season of Famine", "curseunhallowedamuleticon.png", "The Merchant offers 50% fewer choices", false },
    { "Sharpened Arrowhead", "cursesharpenedarrowheadicon.png", "You have no Armour", false },
    { "Shattered Shield", "curseshatteredshieldicon.png", "You have 50% less Energy Shield", false },
    { "Spiked Exit", "cursespikedentranceicon.png", "Take X Physical Damage on Room Completion", false },
    { "Spiked Shell", "cursespikedshellicon.png", "Monsters have 50% increased Maximum Life", false },
    { "Suspected Sympathiser", "afflictionsuspectedsympathisericon.png", "50% reduced Honour restored", false },
    { "Tattered Blindfold", "cursetatteredblindfoldicon.png", "90% reduced Light Radius\nMinimap is hidden", false },
    { "Trade Tariff", "afflictiontradetariffficon.png", "50% increased Merchant prices", false },
    { "Tradition's Demand", "afflictiontraditionsdemandicon.png", "The Merchant only offers one choice", false },
    { "Unassuming Brick", "curseunassumingbrickicon.png", "You cannot gain any more Boons", true },
    { "Unquenched Thirst", "afflictionunquenchedthirsticon.png", "You cannot gain Sacred Water", true },
    { "Untouchable", "afflictionuntouchableicon.png", "You are Cursed with Enfeeble", false },
    { "Veiled Sight", "curseveiledsighticon.png", "Rooms are unknown on the Trial Map", true },
    { "Weakened Flesh", "afflictionweakenedfleshicon.png", "25% less Maximum Honour", false },
    { "Winter Drought", "afflictionwinterdroughticon.png", "Lose all Sacred Water on floor completion", false },
    { "Worn Sandals", "cursewornsandalsicon.png", "30% less Movement Speed if you've been Hit by an Enemy Recently", false },
};

// Every SanctumPersistentEffects curse row: dat Id -> EN display name.
// Canonicalizes room afflictions read from a localized client, so the
// EN-keyed weight tables and this catalog keep working.
struct AfflictionIdName { const char* id; const char* name; };
inline constexpr AfflictionIdName kAfflictionIds[] = {
    { "AfflictionAfflictionOnGainAffliction", "Myriad Aspersions" },
    { "AfflictionAfflictionOnUseFountain", "Costly Aid" },
    { "AfflictionBoonConveretedToMinorAffliction", "Glass Shard" },
    { "AfflictionCannotGainSacredWater", "Unquenched Thirst" },
    { "AfflictionCannotRestoreHonour", "Branded Balbalakh" },
    { "AfflictionDamageTakenOnLowLife", "Dishonoured Tattoo" },
    { "AfflictionHideRoomAffliction", "Purple Smoke" },
    { "AfflictionHideRoomAll", "Veiled Sight" },
    { "AfflictionHideRoomEncounter", "Red Smoke" },
    { "AfflictionHideRoomReward", "Golden Smoke" },
    { "AfflictionHonourLossIsFatal1", "Ghastly Scythe" },
    { "AfflictionHonourLossIsFatal2", "Ghastly Scythe" },
    { "AfflictionHonurLossIsFatal3", "Ghastly Scythe" },
    { "AfflictionLessDamage", "Blunt Sword" },
    { "AfflictionLessMaxHonour", "Weakened Flesh" },
    { "AfflictionLessSacredWater", "Low Rivers" },
    { "AfflictionLose%LifeAndEnergyShieldOnRoomCompletion", "Spiked Exit" },
    { "AfflictionLoseAllSacredWaterOnFloorComplete", "Winter Drought" },
    { "AfflictionLoseLifeAndEnergyShieldInXRooms1", "Death Toll" },
    { "AfflictionLoseLifeAndEnergyShieldInXRooms2", "Death Toll" },
    { "AfflictionLoseLifeAndEnergyShieldInXRooms3", "Death Toll" },
    { "AfflictionLoseLifeAndEnergyShieldInXRooms4", "Death Toll" },
    { "AfflictionLoseLifeAndEnergyShieldInXRooms5", "Death Toll" },
    { "AfflictionLoseLifeAndEnergyShieldInXRooms6", "Death Toll" },
    { "AfflictionLoseLifeAndEnergyShieldInXRooms7", "Death Toll" },
    { "AfflictionLoseLifeAndEnergyShieldInXRooms8", "Death Toll" },
    { "AfflictionLoseSacredWaterOnRoomComplete", "Gate Toll" },
    { "AfflictionLoseSacredWaterWhenDamaged", "Leaking Waterskin" },
    { "AfflictionMerchantCost", "Trade Tariff" },
    { "AfflictionMerchantFewerChoices", "Season of Famine" },
    { "AfflictionMerchantOneItem", "Tradition's Demand" },
    { "AfflictionMonsterLife", "Spiked Shell" },
    { "AfflictionMonsterMoreDamage", "Honed Claws" },
    { "AfflictionMonsterPercentageDamage", "Hungry Fangs" },
    { "AfflictionMonsterPetrifyOnHit", "Chiselled Stone" },
    { "AfflictionMonsterSpeed", "Fiendish Wings" },
    { "AfflictionMonstersBindingChainsOnHit", "Chains of Binding" },
    { "AfflictionMonstersEnfeebled", "Untouchable" },
    { "AfflictionMonstersKnockback", "Rusted Mallet" },
    { "AfflictionNoArmour", "Sharpened Arrowhead" },
    { "AfflictionNoDefences", "Corrosive Concoction" },
    { "AfflictionNoEnergyShield", "Shattered Shield" },
    { "AfflictionNoEvasion", "Iron Manacles" },
    { "AfflictionNoHonourRecoveredThisFloor", "Haemorrhage" },
    { "AfflictionNoMinimap", "Tattered Blindfold" },
    { "AfflictionNoSacredWaterFromChests", "Exhausted Wells" },
    { "AfflictionNoSacredWaterFromMonsters", "Death Toll" },
    { "AfflictionPreventBoons", "Unassuming Brick" },
    { "AfflictionReducedEffectOfRelics", "Forgotten Traditions" },
    { "AfflictionReducedHonourRestored", "Suspected Sympathiser" },
    { "AfflictionReducedMovementSpeed", "Worn Sandals" },
    { "AfflictionRelicsHaveNoEffect", "Orb of Negation" },
    { "AfflictionTrapDamage", "Dark Pit" },
    { "AfflictionTrapDamageMajor", "Deadly Snare" },
    { "AfflictionTrapSpeed", "Rapid Quicksand" },
    { "AfflictionViewRoomsAhead", "Black Smoke" },
    { "AfflictionWrongRoom", "Deceptive Mirror" },
    { "PenaltyDefiedDeathWithLessHonour", "Orbala's Leathers" },
};

inline const AfflictionInfo* FindAffliction(const char* name) {
    if (!name || !name[0]) return nullptr;
    for (const auto& a : kAfflictions)
        if (std::strcmp(a.name, name) == 0) return &a;
    return nullptr;
}

inline const char* AfflictionNameForRowId(const char* rowId) {
    if (!rowId || !rowId[0]) return nullptr;
    for (const auto& e : kAfflictionIds)
        if (std::strcmp(e.id, rowId) == 0) return e.name;
    return nullptr;
}

} // namespace sekhema
